main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recommendationsystem.urls', namespace='recommendationsystem'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/recommendationsystem/urls.py
from django.urls import path
from .views import index, SignUpUser, LoginUser, LogoutUser, search, rate_location, location_recs, about,New_Rec

app_name = 'recommendationsystem'

urlpatterns = [
    path('', index, name='home'),
    path('register/', SignUpUser, name='register'),
    path('login/', LoginUser, name='login'),
    path('logout/', LogoutUser, name='logout'),
    path('search/', search, name='search'),
    path('rate-location/', rate_location, name='rate_location'),
    path('recommendations/', New_Rec, name='recommendations'),
    path('about/', about, name='about'),
]

main/recommendationsystem/models.py
from django.db import models
from django.contrib.auth import get_user_model

import jsonfield
import json
import numpy as np

User = get_user_model()


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    array = jsonfield.JSONField()
    arrayratedlocationsindxs = jsonfield.JSONField()
    name = models.CharField(max_length=1000)
    lastrecs = jsonfield.JSONField()

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        create = kwargs.pop('create', None)
        recsvec = kwargs.pop('recsvec', None)
        print('create:', create)
        if create == True:
            super(UserProfile, self).save(*args, **kwargs)

        elif recsvec is not None and len(recsvec) != 0:
            # self.lastrecs = json.dumps(recsvec.tolist())
            self.lastrecs = json.dumps(recsvec)
            super(UserProfile, self).save(*args, **kwargs)
        else:
            nlocations = LocationData.objects.count()
            array = np.zeros(nlocations)
            ratedlocations = self.ratedlocations.all()
            self.arrayratedlocationsindxs = json.dumps([loc.locationindx for loc in ratedlocations])
            for loc in ratedlocations:
                array[loc.locationindx] = loc.value
            self.array = json.dumps(array.tolist())
            super(UserProfile, self).save(*args, **kwargs)


class LocationRated(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='ratedlocations')
    location = models.ForeignKey('LocationData', on_delete=models.CASCADE)
    locationindx = models.IntegerField(default=-1)
    value = models.IntegerField()

    def __str__(self):
        return self.location.title


class LocationData(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='location/', null=True, blank=True)
    address = models.CharField(max_length=150)
    array = jsonfield.JSONField()
    ndim = models.IntegerField(default=300)
    description = models.TextField()

main/recommendationsystem/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    email = forms.CharField(widget=forms.EmailInput, required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        if password == password2:
            try:
                User.objects.get(username__iexact=username, email__iexact=email)
            except User.DoesNotExist:
                return cleaned_data
            raise forms.ValidationError("This username already exists.")
        else:
            raise forms.ValidationError("Passwords do not match.")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class UserLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

main/recommendationsystem/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth import get_user_model
from .models import LocationData, UserProfile, LocationRated
from django.core.paginator import Paginator

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from django.core.cache import cache
import numpy as np
import pandas as pd
from ast import literal_eval
import copy
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import WordPunctTokenizer

tknzr = WordPunctTokenizer()
nltk.download('stopwords')
stoplist = stopwords.words('english')
from nltk.stem.porter import PorterStemmer

from scipy.stats import pearsonr
from scipy.spatial.distance import cosine

# umatrixpath = '/mnt/c/Users/psychogyio/Desktop/andrea/machine_learning_for_the_web-master_3/chapter_7/server_locationrecsys/umatrix.csv'

nlocationsperquery = 10
nminimumrates = 5
numrecs = 5
recmethod = 'cf_itembased'

User = get_user_model()


def PreprocessTfidf(texts, stoplist=[], stem=False):
    newtexts = []
    for text in texts:
        if stem:
            tmp = [w for w in tknzr.tokenize(text) if w not in stoplist]
        else:
            tmp = [stemmer.stem(w) for w in [w for w in tknzr.tokenize(text) if w not in stoplist]]
        newtexts.append(' '.join(tmp))
    return newtexts


def index(request):
    return render(request, 'home.html')


def SignUpUser(request):
    form = UserRegisterForm()

    if request.method == 'GET':
        context = {'form': form}
        return render(request, 'signup.html', context)

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            uprofile = UserProfile()
            uprofile.user = user
            uprofile.name = user.username
            uprofile.save(create=True)
            username = form.cleaned_data['username']
            messages.success(request, f'Registered successfully as {username}')
            return redirect("recommendationsystem:login")
        else:
            for msg in form.errors:
                messages.error(request, form.errors[msg].as_text())
                return redirect("recommendationsystem:register")


def LoginUser(request):
    if request.method == 'POST':
        print(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            return redirect('recommendationsystem:search')
        else:
            messages.error(request, "Invalid username or password.")
            return redirect('recommendationsystem:login')
    return render(request, "login.html")


def LogoutUser(request):
    logout(request)
    messages.success(request, 'Logged out successfully')
    return redirect('recommendationsystem:login')


def search(request):
    # if not request.user.is_authenticated:
    #     messages.error(request, 'You must be logged in to view this page.')
    #     return redirect('recommendationsystem:login')
    if request.method == 'GET':
        data = request.GET.get('q', None)
        if data is None:
            # context = {
            #     'msg': 'Please make sure you rate 5 locations from the search list.'
            # }
            return render(request, 'search.html')
        else:
            print(data)
            titles = cache.get('titles')
            if titles is None:
                texts = []
                locations = LocationData.objects.all()
                ndim = locations[0].ndim
                matr = np.empty([1, ndim])
                titles_list = []
                cnt = 0
                for loc in locations[:]:
                    texts.append(loc.description)
                    newrow = np.array(loc.array)
                    if cnt == 0:
                        matr[0] = newrow
                    else:
                        matr = np.vstack([matr, newrow])
                    titles_list.append(loc.title)
                    cnt += 1
                vectorizer = TfidfVectorizer(min_df=1, max_features=True)
                processedtexts = PreprocessTfidf(texts, stoplist, True)
                model = vectorizer.fit(processedtexts)
                cache.set('model', model)
                cache.set('data', matr)
                cache.set('titles', titles_list)
            else:
                print('loaded', str(len(titles)))

            Umatrix = cache.get('umatrix')
            if Umatrix.any() == None:
                df_umatrix = pd.read_csv(umatrixpath)
                Umatrix = df_umatrix.values[:, 1:]
                print('umatrix:', Umatrix.shape)
                cache.set('umatrix', Umatrix)
                cf_itembased = CF_itembased(Umatrix)
                cache.set('cf_itembased', cf_itembased)

            # load all locations vectors/titles
            matr = cache.get('data')
            print('matr', len(matr))
            titles = cache.get('titles')
            print('ntitles:', len(titles))
            model_tfidf = cache.get('model')

            # load in cache rec sys methods
            print('load methods...')

            # find locations similar to the query
            # print 'names:',len(model_tfidf.get_feature_names())
            queryvec = model_tfidf.transform([data.lower().encode('ascii', 'ignore')]).toarray()

            # print 'vec:', queryvec

            sims = cosine_similarity(queryvec, matr)[0]
            indxs_sims = list(sims.argsort()[::-1])
            # print indxs_sims
            titles_query = list(np.array(titles)[indxs_sims][:nlocationsperquery])
            if not titles_query:
                found = False
            else:
                found = True
                locations = list(zip(titles_query, indxs_sims[:nlocationsperquery]))
                locations_li = []
                for loc, indx in locations:
                    location_obj = LocationData.objects.get(title=loc)
                    locations_li.append(location_obj)
            show_rec_btn = False
            if request.user.is_authenticated:
                user_profile = UserProfile.objects.get(user=request.user)
                rated_locations = user_profile.ratedlocations.all()
                msg = f"Rated Locations: {len(rated_locations)}"
                if len(rated_locations) < nminimumrates:
                    min_rated_msg = f"{nminimumrates - len(rated_locations)} more locations left to be rated."
                elif len(rated_locations) >= nminimumrates:
                    min_rated_msg = "Minimum criteria satisfied !!"
                    show_rec_btn = True

            context = {
                'locations': locations,
                'rates': [1, 2, 3, 4, 5],
                'found': found,
                'locations_list': locations_li,
                'msg': msg,
                'min_rated_msg': min_rated_msg,
                'show_rec_btn': show_rec_btn
            }

            return render(
                request, 'search.html', context)


def RemoveFromList(liststrings, string):
    outlist = []
    for s in liststrings:
        if s == string:
            continue
        outlist.append(s)
    return outlist


def rate_location(request):
    if request.user.is_authenticated:
        rate = request.GET.get("vote")
        locations = request.GET.get("locations")
        location = request.GET.get("location")
        location_indx = request.GET.get("locationindx")
        locations, locationsindxs = list(zip(*literal_eval(locations)))
        locationindx = int(location_indx)

        # save location rating

        userprofile = UserProfile.objects.get(user=request.user)
        location_obj = LocationData.objects.get(title=location)

        if LocationRated.objects.filter(location=location_obj).filter(user=userprofile).exists():
            lr = LocationRated.objects.get(location=location_obj, user=userprofile)
            lr.value = int(rate)
            lr.save()
        else:
            lr = LocationRated()
            lr.user = userprofile
            lr.value = int(rate)
            lr.location = location_obj
            lr.locationindx = locationindx
            lr.save()

        userprofile.save()
        rated_locations = userprofile.ratedlocations.all()
        msg = f"Locations Rated: {len(rated_locations)}"
        show_rec_btn = False
        if len(rated_locations) < nminimumrates:
            min_rated_msg = f"{nminimumrates - len(rated_locations)} more locations left to be rated."
        elif len(rated_locations) >= nminimumrates:
            min_rated_msg = "Minimum criteria satisfied !!"
            show_rec_btn = True

        locations = RemoveFromList(locations, location)
        # print(locations)
        locationsindxs = RemoveFromList(locationsindxs, locationindx)
        locations_li = []
        for loc in locations:
            location_obj = LocationData.objects.get(title=loc)
            locations_li.append(location_obj)
        context = {"locations": list(zip(locations, locationsindxs)),
                   "found": True,
                   "rates": [1, 2, 3, 4, 5],
                   "locations_list": locations_li,
                   "msg": msg,
                   "min_rated_msg": min_rated_msg,
                   "show_rec_btn": show_rec_btn}
        return render(
            request, 'search.html', context)
    else:
        messages.info(request, "You must be logged in to rate a location.")
        return redirect('recommendationsystem:search')


def location_recs(request):
    userprofile = None
    if request.user.is_authenticated:

main/recommendationsystem/templates/about.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
<h1>About Page</h1>
</div>
{% endblock %}

main/recommendationsystem/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

     <!--Import main.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style>
        #toast-container {
            max-width: 30% !important;
            top: 25% !important;
            left: 2% !important;
            margin: auto;
        }
    </style>
</head>

<body>
<div class="navbar-fixed">
 <nav class="teal lighten-2">
    <div class="nav-wrapper">
      <a href="{% url 'recommendationsystem:home' %}" class="brand-logo center">Home</a>
      <ul class="left hide-on-med-and-down">
        <li><a href="{% url 'recommendationsystem:about' %}">About</a></li>
        {% if request.user.is_authenticated%}
            <li><a href="{% url 'recommendationsystem:logout' %}">Logout<span class="badge yellow">{{ request.user.username }}</span></a></li>
            <li><a href="{% url 'recommendationsystem:recommendations' %}">My Recommendations</a></li>
            <li><a href="{% url 'recommendationsystem:search' %}">Search</a></li>
        {% else %}
            <li><a href="{% url 'recommendationsystem:register' %}">Signup</a></li>
            <li><a href="{% url 'recommendationsystem:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
 </nav>
</div>



 {% block content %}
 {% endblock %}


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!--JavaScript at end of body for optimized loading-->
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
{% include 'messages.html' %}


<script type="text/javascript">
    const currentLocation = location.href;
    const navBarItem = document.querySelectorAll('ul.left li a');
    const navBarItemLength = navBarItem.length;
    console.log(navBarItem);
    for (let i = 0; i < navBarItemLength; i++){
        if(navBarItem[i].href === currentLocation){
            console.log(navBarItem[i].parentNode);
            navBarItem[i].parentNode.className = "active";
        }
    }
</script>

{% block script %}
{% endblock %}


</body>
</html>

main/recommendationsystem/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% load my_filters %}

{% block content %}


<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        <br><br>
        <div class="row">
            <div class="col l4 push-l4">
                <h1 class="header center deep-purple-text">WELCOME</h1>
            </div>
        </div>
        <div class="row center">
            <h5 class="header col s12 light teal-text text-lighten-1">search the best locations around kathmandu</h5>
        </div>
    </div>
</div>

<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <form method="get">
          <i class="material-icons prefix">search</i>
          <input type="text" id="search-input" name="q">
          <label for="search-input">search by title, description etc.</label>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="container">
<!--    <h3 class="center-align">Search results</h3>-->
<!--    <div class="row"></div>-->
    <h3 class="center-align green-text">Make sure to rate any 5 locations from the search list !</h3>

    {% if msg %}
    <div class="row">
        <div class="col l5 push-l3">
            <h4 class=" section center-align purple-text">{{msg}}</h4>
        </div>
    </div>
    {% endif %}

    {% if min_rated_msg %}
    <div class="row">
    <div class="col l5 push-l3">
        <h6 class="section center-align orange">{{min_rated_msg}}</h6>
    </div>
    </div>
    {% endif %}
    {% if show_rec_btn == True %}
    <div class="row container">
    <div class="col l5 push-l4">
        <a class="btn green pulse" href="{% url 'recommendationsystem:recommendations' %}">View recommendations?</a>
    </div>
    </div>
    {% endif %}



    <div class="row">
        {% if found == True %}
        <h3 class="center-align">Search results</h3>
        <div class="divider"></div>
        {% for location, locindx in locations %}
        <div class="col l4">
            <div class="card small hoverable z-depth-2">
                {% for loc in locations_list %}
                {% if loc.title == location %}
                <div class="card-image">
                    <img src="{{ loc.image.url }}" alt="">
                </div>
                {% endif %}
                {% endfor %}
                <div class="card-content">
                    <span class="card-title activator center-align truncate"><strong>{{ location }}</strong><i class="material-icons right">more_vert</i></span>
                    <div class="card-action">
                        <a href="#" class="btn activator">Rate location</a>
                        <a class="waves-effect waves-light btn modal-trigger" href="#modal-{{location}}">View Details</a>
                    </div>
                </div>
                {% for loc in locations_list %}
                {% if loc.title == location %}
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">{{ loc.title }}<i class="material-icons right">close</i></span>
                    <p class="truncate">{{ loc.description }}</p>
                    <h4>Rate:</h4>
                    {% for r in rates %}
                    <a class="btn-floating hoverable green center" href="{% url 'recommendationsystem:rate_location'  %}?vote={{r}}&locations={{locations}}&location={{location}}&locationindx={{locindx}}">{{r}}</a>
                    {% endfor %}
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        {% elif found == False %}
            <h3 class="center-align red-text">No matching results found!</h3>
        {% endif %}

    </div>
</div>


{% for loc in locations_list %}
<!-- Modal Structure -->
<div id="modal-{{loc.title}}" class="modal">
    <div class="modal-content">
        <h4 class="center">{{loc.title}}</h4>
        <p>{{loc.description}}</p>
        <div class="divider"></div>
        <div class="row section">
            <h4 class="center">Location Photo</h4>
            <div class="col push-l3">
                <img class="materialboxed" width="650" src="{{loc.image.url}}">
            </div>
        </div>
        <div class="divider"></div>
        <h4>Users Ratings:</h4>
        {% if loc.locationrated_set.all.count != 0 %}
        {% for rat_loc in loc.locationrated_set.all %}
        <div class="row">
            <h6 class="align-center">{{rat_loc.user.user.username}}: {% for i in rat_loc.value|times%}<i class="material-icons green-text">star</i>{% endfor %}</h6>
        </div>
        {% endfor %}
        {% else %}
        <div class="row">
            <h6 class="align-center"><strong>No users have rated this location currently!</strong></h6>
        </div>
        {% endif %}
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
</div>

{% endfor %}

{% endblock %}


{% block script %}
<script>
$(document).ready(function(){
    $('.modal').modal();
    $('.materialboxed').materialbox();
});
</script>
{% endblock %}

main/recommendationsystem/templates/signup.html
{% extends 'base.html' %}


{% block content %}

<!--<div class="container">-->

<!--    <div class="row">-->
<!--        <div class="col s12 l8">-->
<!--            <div class="card z-depth-4">-->
<!--                <div class="card-content center-align">-->
<!--                    <span class="card-title"><h3 class="teal-text text-lighten-1">Sign up</h3></span>-->
<!--                    <div class="row">-->
<!--                        <form class="col s12" method="post" action="{% url 'recommendationsystem:register' %}">-->
<!--                            {% csrf_token %}-->

<!--                            <div class="row">-->
<!--                                <div class="input-field col s12">-->
<!--                                    <i class="material-icons prefix">person</i>-->
<!--                                    {{form.username}}-->
<!--                                    <label for="id_username">Username</label>-->
<!--                                </div>-->
<!--                            </div>-->

<!--                            <div class="row">-->
<!--                                <div class="input-field col s6">-->
<!--                                    <i class="material-icons prefix">person</i>-->
<!--                                    {{form.first_name}}-->
<!--                                    <label for="id_first_name">First Name</label>-->
<!--                                </div>-->
<!--                                <div class="input-field col s6">-->
<!--                                    {{form.last_name}}-->
<!--                                    <label for="id_last_name">Last Name</label>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                            <div class="row">-->
<!--                                <div class="input-field col s12">-->
<!--                                    <i class="material-icons prefix">mail</i>-->
<!--                                    {{form.email}}-->
<!--                                    <label for="id_email">Email</label>-->
<!--                                </div>-->
<!--                            </div>-->

<!--                            <div class="row">-->
<!--                                <div class="input-field col s12">-->
<!--                                    <i class="material-icons prefix">lock</i>-->
<!--                                    {{form.password}}-->
<!--                                    <label for="id_password">Password</label>-->
<!--                                </div>-->
<!--                            </div>-->
<!--&lt;!&ndash;                            <div class="row">&ndash;&gt;-->
<!--&lt;!&ndash;                                <div class="input-field col s12">&ndash;&gt;-->
<!--&lt;!&ndash;                                    <i class="material-icons prefix">lock</i>&ndash;&gt;-->
<!--&lt;!&ndash;                                    {{form.password2}}&ndash;&gt;-->
<!--&lt;!&ndash;                                    <label for="id_password2">Confirm Password</label>&ndash;&gt;-->
<!--&lt;!&ndash;                                </div>&ndash;&gt;-->
<!--&lt;!&ndash;                            </div>&ndash;&gt;-->
<!--                            <div class="row">-->
<!--                                <div class="input-field col s12">-->
<!--                                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit-->
<!--                                        <i class="material-icons right">send</i>-->
<!--                                    </button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->


<!--<div class="row center-content">-->
<!--  <div class="col card hoverable">-->
<!--    <form method="post" action="{% url 'recommendationsystem:register' %}">-->
<!--      {% csrf_token %}-->
<!--      <div class="card-content center-align">-->
<!--        <span class="card-title"><h3 class="teal-text text-lighten-1">Sign up</h3></span>-->
<!--        <div class="row">-->
<!--            <div class="input-field col s12">-->
<!--                <i class="material-icons prefix">person</i>-->
<!--                {{form.username}}-->
<!--                <label for="id_username">Username</label>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="input-field col s6">-->
<!--                <i class="material-icons prefix">person</i>-->
<!--                {{form.first_name}}-->
<!--                <label for="id_first_name">First Name</label>-->
<!--            </div>-->
<!--            <div class="input-field col s6">-->
<!--                {{form.last_name}}-->
<!--                <label for="id_last_name">Last Name</label>-->
<!--            </div>-->
<!--        </div>-->
<!--          <div class="row">-->
<!--              <div class="input-field col s12">-->
<!--                  <i class="material-icons prefix">mail</i>-->
<!--                  {{form.email}}-->
<!--                  <label for="id_email">Email</label>-->
<!--              </div>-->
<!--          </div>-->

<!--          <div class="row">-->
<!--              <div class="input-field col s12">-->
<!--                  <i class="material-icons prefix">lock</i>-->
<!--                  {{form.password}}-->
<!--                  <label for="id_password">Password</label>-->
<!--              </div>-->
<!--          </div>-->
<!--          <div class="row">-->
<!--              <div class="input-field col s12">-->
<!--                  <i class="material-icons prefix">lock</i>-->
<!--                  {{form.password2}}-->
<!--                  <label for="id_password2">Confirm Password</label>-->
<!--              </div>-->
<!--          </div>-->
<!--      </div>-->
<!--      <div class="card-action right-align">-->
<!--        <input type="reset" id="reset" class="btn-flat grey-text waves-effect">-->
<!--        <button type="submit" class="btn teal waves-effect waves-light">Signin-->
<!--          <i class="material-icons right">send</i>-->
<!--        </button>-->
<!--      </div>-->
<!--    </form>-->
<!--  </div>-->
<!--</div>-->
<div class="row center-content">
    <div class="col card hoverable m5 l4 offset-l4">
        <form method="post">{% csrf_token %}
            <div class="card-content center-align">
                <span class="card-title"><h3 class="teal-text text-lighten-1">Sign up</h3></span>
                <div class="row">
                    <div class="input-field col m12 s10 l12">
                        <i class="material-icons prefix">person</i>
                        {{form.username}}
                        <label for="id_username">Username</label>
                    </div>
                    <div class="input-field col s4 m6 l6">
                        <i class="material-icons prefix">person</i>
                        {{form.first_name}}
                        <label for="id_first_name">First Name</label>
                    </div>
                    <div class="input-field col s4 m6 l6">
                        {{form.last_name}}
                        <label for="id_last_name">Last Name</label>
                    </div>
                    <div class="input-field col s4 m6 l12">
                        <i class="material-icons prefix">mail</i>
                        {{form.email}}
                        <label for="id_email">Email</label>
                    </div>
                    <div class="input-field col s4 m6 l12">
                        <i class="material-icons prefix">lock</i>
                        {{form.password}}
                        <label for="id_password">Password</label>
                    </div>
                    <div class="input-field col s4 m12 l12">
                        <i class="material-icons prefix">lock</i>
                        {{form.password2}}
                        <label for="id_password2">Confirm Password</label>
                    </div>
                </div>
            </div>

            <div class="card-action right-align">
                <input type="reset" id="reset" class="btn-flat grey-text waves-effect waves-teal">
                <button type="submit" class="btn teal waves-effect waves-light">Sign in
                    <i class="material-icons right">send</i>
                </button>
            </div>
    </div>
    </form>
  </div>
</div>


{% endblock %}

{% block script %}
<script>
    $("#reset").on("click", function() {
      $('label').removeClass('active');
    });
</script>
{% endblock %}